# Problem Statement
# Consider all integer combinations of a**b for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5
# If they are then placed in numerical order, with any repeats removed, 
# we get the following sequence of 15 distinct terms:
# 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
# How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

def main
  start_time = Process.clock_gettime(Process::CLOCK_MONOTONIC)

  arr = []
  for a in 2..100
    for b in 2..100
      arr << a**b
    end
  end
  
  arr.uniq!
  print "There are #{arr.length} distinct terms in the sequence generated by a**b"
  print "for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100 \n"

  finish_time = Process.clock_gettime(Process::CLOCK_MONOTONIC)
  @runtime = finish_time - start_time
  puts "Problem computed in #{@runtime}s"
end

main
#=> 9183
# 0.008775962000072468s
