# Problem Statement:
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2 and
# by considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

def sum_of_even_fibonacci_numbers()
  arr = [1, 2]
  num = 3

  while num < 4000000
    arr << num
    old_term = arr[-2]
    new_term = arr[-1]
    num = old_term + new_term
  end
  arr.reduce(0) {|acc, e| e.even? ? acc + e : acc}
end

p "The sum of the even-valued terms in the Fibonacci sequence whose values do not exceed four million is: #{sum_of_even_fibonacci_numbers}" #=> 4613732